// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-z82C_9KRvzeubcYeTwv6L_Sjm8FI6c',
    appId: '1:961556762197:web:1300c443af1cbaa8838edc',
    messagingSenderId: '961556762197',
    projectId: 'ahome-57b83',
    authDomain: 'ahome-57b83.firebaseapp.com',
    storageBucket: 'ahome-57b83.appspot.com',
    measurementId: 'G-MEK0L42H9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4ZaPAXdJHzUL6qGnw2C_Tvyp8A-TFm0',
    appId: '1:961556762197:android:4314ff7e8612fd34838edc',
    messagingSenderId: '961556762197',
    projectId: 'ahome-57b83',
    storageBucket: 'ahome-57b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2bbSPU5hUirrppwOL_3MomoFi9bZklg',
    appId: '1:961556762197:ios:03a515043eba4ddd838edc',
    messagingSenderId: '961556762197',
    projectId: 'ahome-57b83',
    storageBucket: 'ahome-57b83.appspot.com',
    iosBundleId: 'com.example.ahome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2bbSPU5hUirrppwOL_3MomoFi9bZklg',
    appId: '1:961556762197:ios:819b029e28d3d4b9838edc',
    messagingSenderId: '961556762197',
    projectId: 'ahome-57b83',
    storageBucket: 'ahome-57b83.appspot.com',
    iosBundleId: 'com.example.ahome.RunnerTests',
  );
}
